### ISSUE TITLE
semicolon ;

### ISSUE THREAD

**Issue by moithil** [GeekTrainer/Flask#1]
Why have you used semicolon (;) in places in tutorial for flask.
I have followed your python tutorial in MVA and now this flask too, but i am not getting why have you used these semicolons in places. 
Well i'm new to github and don't know if this is the right way to contact.

**Comment by hockeygeekgirl** [comment]
Some programming languages require a semi colon at the end of a line of code (C# requires it). Python is a forgiving language (which is one of the reasons it is popular with beginners) so you can put a semi colon at the end of a line of code of you want, our not. The code works regardless. Because Christopher and I have both coded in C# we may use the semi colon sometimes without realizing we have done it.  Christopher in fact prefers to always end each line of code with a semi colon, I tend not to.

Hope that helps!
Susan

Sent from my Windows Phone

**Comment by moithil** [comment]
Yep, thank you.

**Comment by Cediddi** [comment]
Python is not "forgiving". It's an odd and usually disliked feature. Semicolon is not a line terminator, it's a separator for compound statements is strongly opposed in the community. PEP8 says, "Compound statements (multiple statements on the same line) are generally discouraged". By generally, they're meaning, if your "if" statement is so simple and the result is also simple, it's generally "ok" to use compound statements, like this:

if a<b: print("a is small")

But when your statement is longer, more complex or multi-line or multi-statement.

I really think you, as a trainer, are teaching a very very odd thing to your students as it's a normal thing. Please revise this code and put a warning in your video as  'using ";" is strongly discouraged' and warn each other in future. You are not writing C#. Warn me, if I ever write C# like I write Python. Different languages require different paradigms.

**Comment by GeekTrainer** [comment]
Thanks for your feedback. You'll notice we don't use semicolons any longer. :-)
